### ISSUE TITLE
JWTを使った認証について

### ISSUE THREAD

**Issue by okada-shun** [okada-shun/game-api#1]
JWTとはJSON Web Tokenの略である。
ヘッダー、ペイロード、署名の三つの要素で構成され、それぞれBase64urlでエンコードされている。xxxxx.yyyyy.zzzzzのように、三つの要素はそれぞれドットで結合されている。

ヘッダーは通常、署名アルゴリズム（HMACSHA256など）とトークンタイプ（JWT）の二つの部分で構成されている。
例えば、
{
  "alg": "HS256",
  "typ": "JWT"
}
このようなJSONである。このJSONをBase64urlでエンコードし、JWTのヘッダーが出来上がる。

ペイロードにはユーザの情報や追加データを含ませることが出来る。例えば、iss（発行者）、 exp（有効期限）、 sub（件名）といったものである。
ペイロードの例は、
{
  "sub": "1234567890",
  "name": "John Doe",
  "admin": true
}
このようなJSONである。このJSONをBase64urlでエンコードし、JWTのペイロードが出来上がる。
署名されたトークンの場合、この情報は改ざんからは保護されるが、誰でも読み取ることが出来る点に注意が必要である。そのため、暗号化しない限り、JWTのペイロードに機密情報を入れてはならない。

署名はヘッダーをエンコードしたものとペイロードをエンコードしたものを連結したものに対して、秘密鍵とヘッダーで指定したアルゴリズムを用いて生成される。署名はメッセージが途中で改ざんされていないことを確認するのに使われる。

これら三つの要素が結合され、JWTが完成する。

ユーザ情報作成APIでは、まず、フロント側がユーザ自身の情報（名前）をサーバー側に送信する。
サーバーはリクエストされたユーザ情報をデータベースに格納し、また、ユーザ情報を基にJWTでトークンを生成する。
生成されたトークンはフロント側に返される。フロント側では、トークンをLocalStorageに保存する。

ユーザ情報取得APIでは、まず、フロント側がサーバーにアクセスする。
サーバーは秘密鍵を用いてトークンを認証し、トークンからユーザIDを取得する。
そして、データベースからそのIDのユーザ情報（名前）を取り出し、フロント側に返す。

ユーザ情報更新APIでは、まず、フロント側がサーバーにアクセスし、更新するユーザ情報（新しい名前）を送信する。
サーバーは秘密鍵を用いてトークンを認証し、トークンからユーザIDを取得する。
そして、データベースのそのIDのユーザ情報（名前）を新しいものに更新する。

**Comment by okada-shun** [comment]
ユーザ情報作成APIでは、まず、フロント側がユーザ自身の情報（名前）をサーバー側に送信する。サーバーはリクエストされたユーザ情報をデータベースに格納し、また、ユーザ情報を基にJWTでトークンを生成する。生成されたトークンはフロント側に返される。フロント側では、トークンをLocalStroageに保存する。

**Comment by GuiltyMorishita** [comment]
メリット・デメリットを洗い出して、検討数

**Comment by okada-shun** [comment]
JWTのメリット
サイズが小さく、二つのエンティティ間で迅速に受け渡しが出来る。
トークンの中に署名が含まれているため、改ざんがあってもそれをチェック出来るようになっている。
認証に必要となる情報がトークンの中に含まれているため、データベース問い合わせを行う必要がない。

JWTのデメリット
トークンの改ざん認証しかしていないので、何らかの理由でトークンそのものが流出すると有効期限が切れるまで危険である。
この危険性から、有効期限を短く設定すると、頻繁にトークンの更新リクエストが発生することになる。
トークンの即時無効化が出来ない。
