### ISSUE TITLE
Gitの基本

### ISSUE THREAD

**Issue by okada-shun** [okada-shun/game-api#20]
### 既存ディレクトリでのリポジトリの初期化
次のように実行する。
`$ git init`
これにより.gitという名の新しいサブディレクトリが作られ、リポジトリに必要な全てのファイルがその中に格納される。

### 既存のリポジトリのクローン
既存のGitリポジトリのコピーを取得したい場合は`git clone [url]`のように実行する。
`$ git clone https://github.com/libgit2/libgit2`
これによりlibgit2というディレクトリが作成され、その中で .git ディレクトリが初期化される。そしてリポジトリのすべてのデータが引き出され、最新の作業コピーがチェックアウトされる。 新しく出来たlibgit2 ディレクトリに入ると、このプロジェクトのファイルを見ることが出来る。

## 変更内容のリポジトリへの記録

作業コピー内の各ファイルには追跡されている(tracked)ものと、追跡されてない(untracked)ものの二通りがある。追跡されているファイルには、「変更されていない(unmodified)」、「変更されている(modified)」、「ステージされている(staged)」の三つの状態がある。追跡されていないファイルはそのどの状態でもない。最初にプロジェクトをクローンした時点では、全てのファイルは「追跡されている」かつ「変更されていない」状態となる。
「変更されていない」ファイルを編集すると、そのファイルは「変更されている」ファイルになる。そして、そのファイルをステージすると「ステージされている」ファイルになり、コミットすると「変更されていない」ファイルに状態が戻る。

### ファイル状態の確認
次のように実行する。
`$ git status`

### 新しいファイルの追跡
新しいファイルの追跡を開始するには`git add`コマンドを使用する。
`$ git add README`
これによりREADMEファイルは追跡対象になり、ステージされる。そしてコミットを行えるようになる。

### 変更したファイルのステージング
変更したファイルをステージするには同じく`git add`コマンドを使用する。

### 状態表示の簡略化
`git status -s`や`git status --short`コマンドで実行できる。

### ファイルの無視
`.gitignore`ファイルを作成し、その中に無視させたいファイルのパターンを並べる。

### ステージされている変更 / されていない変更の閲覧
`git diff`コマンドで、変更したがまだステージしていない内容を見ることが出来る。
`git diff --staged` コマンドで、ステージされている変更と直近のコミットの内容を比較できる。

### 変更のコミット
ステージされたファイルをコミットするには`git commit`コマンドを使用する。`-m`フラグに続けてコミットメッセージを記述することができる。
`$ git commit -m "Story 182: Fix benchmarks for speed"`

### ステージングエリアの省略
`git commit -a`コマンドで`git add`を省略できる。

### ファイルの削除
`git rm`コマンドで、ファイルをGitから削除することができる。ファイルを追跡対象からはずし、コミットする。

### ファイル名の変更
`git mv`コマンドで実行できる。
`$ git README.md README`
これは次と同等の操作である。
```
$ mv README.md README
$ git rm README.md
$ git add README
```

### コミット履歴の閲覧
`git log`コマンドが履歴閲覧の最も簡単な方法である。これには様々なオプションがある。

## 作業のやり直し

コミットをやり直すには`--amend`オプションをつけてもう一度コミットする。
`$ git commit --amend`
一旦コミットした後に、何かのファイルをステージし忘れたことに気付いた場合は次のようにする。
```
$ git commit -m 'initial commit'
$ git add forgotten_file
$ git commit --amend
```
二番目のコミットが一番目のコミットを上書きする。

### ステージしたファイルの取り消し
`git reset HEAD <file>...`コマンドを実行する。

### ファイルへの変更の取り消し
`git checkout -- <file>...`コマンドを実行する。

Git にコミットした内容のすべては、ほぼ常に取り消しが可能であるが、まだコミットしていない内容を失うと、それは二度と取り戻せないことに注意が必要である。

### リモートの表示
`git remote`コマンドで、今までに設定したリモートハンドルの名前が一覧表示される。また、`-v`を指定すると、その名前に対応するURLが、書き込み用と読み取り用の2つ表示される。

### リモートリポジトリの追加
`git remote add <shortname> <url>`コマンドで、新しいリモートGitリポジトリにアクセスしやすいような名前をつけて追加することが出来る。

### リモートからのフェッチ、そしてプル
データをリモートリポジトリから取得するには次のコマンドを実行する。
`$ git fetch [remote-name]`
このコマンドはリモートプロジェクトの全てのデータの中から、まだローカルリポジトリが持っていないものを引き出す。 実行後は、リモートにあるすべてのブランチを参照できるようになり、いつでもマージしたり、中身を調べたりすることが可能となる。
また、`git pull`コマンドを使うと、自動的にフェッチを行い、リモートブランチの内容を現在のブランチにマージする。

### リモートへのプッシュ
`git push [remote-name] [branch-name]`コマンドでリモートへプッシュできる。追加したコミットをoriginサーバーにプッシュしたい場合は、次のように実行する。
`$ git push origin master`
このコマンドが動作するのは、自分が書き込みアクセス権を持つサーバーからクローンし、かつその後誰もそのサーバーにプッシュしていない場合のみである。 自分以外の誰かが同じサーバーからクローンし、誰かが上流にプッシュした後で自分がプッシュしようとすると、拒否される。

### リモートの調査
`git remote show [remote-name]`コマンドで特定のリモートの情報を調べることができる。 

### リモートの削除・名前変更
`git remote rename`コマンドでリモートを参照する名前を変更できる。
`git remote rm`コマンドでリモートを削除できる。

### タグの一覧表示
`git tag`コマンドでタグの一覧表示が出来る。

### タグの作成
Gitのタグには、軽量 (lightweight) 版と注釈付き (annotated) 版の二通りがある。

### 注釈付きのタグ
`tag`コマンドの実行時に`-a`を指定することで、注釈付きのタグを作成できる。`-m`で、タグ付け時のメッセージを指定する。

### 軽量版のタグ
コミットにタグをつけるもうひとつの方法が、軽量版のタグである。 これはコミットのチェックサムだけを保持するもので、それ以外の情報は含まれない。軽量版のタグを作成するには`-a`、`-s`あるいは`-m`といったオプションをつけず`git tag`コマンドを実行する。

### 後からのタグ付け
`$ git tag -a v1.2 [コミットのチェックサム (あるいはその一部)]`のコマンドで後からタグをつけることが出来る。

### タグの共有
デフォルトでは、`git push`コマンドはタグ情報をリモートに送らない。 タグを作ったら、タグをリモートサーバーにプッシュするよう明示する必要があり、`git push origin [tagname]`コマンドを実行する。多くのタグを一度にプッシュする場合は`git push origin --tags`コマンドを実行する。

### タグのチェックアウト
タグのチェックアウトはGitではできない。仮にとある時点でのリポジトリの内容を、 タグ付けされたような形で作業ディレクトリに保持したい場合、`git checkout -b [branchname] [tagname]`を実行すると特定のタグと紐付けたブランチを作成することはできる。

## Git エイリアス

```
$ git config --global alias.co checkout
$ git config --global alias.br branch
$ git config --global alias.ci commit
$ git config --global alias.st status
```
のようにすることで、`git commit`と同じことが単に`git ci`と入力するだけでできるようになる。

### 参考
git --distributed-even-if-your-workflow-isnt
Gitの基本
https://git-scm.com/book/ja/v2/Git-%E3%81%AE%E5%9F%BA%E6%9C%AC-Git-%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE%E5%8F%96%E5%BE%97

**Comment by GuiltyMorishita** [comment]
LGTM
