### ISSUE TITLE
Gitのブランチ機能

### ISSUE THREAD

**Issue by okada-shun** [okada-shun/game-api#21]
## ブランチとは

ブランチとは、開発の本流から分岐し、本流の開発を邪魔することなく作業を続けることを可能にする機能のことである。

### 新しいブランチの作成
`git branch`コマンドを実行することで新しいブランチが作られる。
`$ git branch testing`
これによりtestingブランチが作られた。
Gitにおいて、作業しているローカルブランチへのポインタを指すのがHEADである。

### ブランチの切り替え
`git checkout`コマンドを実行することでブランチを切り替えられる。
`$ git checkout testing`
これによりHEADはtestingブランチを指すようになる。
このtestingブランチで変更を行いコミットを行うと、testingブランチは一つ進むが、一方でmasterブランチは変わらない。`$ git checkout master`でmasterブランチに戻ると、HEADポインタが指す先がmasterブランチに戻る。これにより作業ディレクトリ内のファイルが、masterが指すスナップショットの状態に戻る。ここでmasterブランチで変更を行い、コミットを行うと、testingブランチとプロジェクトの歴史が分岐することになる。

## ブランチとマージの基本

ブランチの作成と新しいブランチへの切り替えを同時に行うには、`git checkout`コマンドに`-b`スイッチをつけて実行する。
`$ git checkout -b iss53`
これによりiss53ブランチが作られ、iss53ブランチへ切り替わった。
これは次のコマンドのショートカットである。
```
$ git branch iss53
$ git checkout iss53
```
また、ブランチを削除するには`git branch`で`-d`オプションを指定する。
`$ git branch -d iss53`

### マージの基本
masterブランチにiss53ブランチをマージするには、masterブランチに切り替えてから、`git merge`コマンドを実行する。
```
$ git checkout master
$ git merge iss53
```
開発の歴史が過去のとある時点で分岐している場合、複数の親を持つ特別なコミットとなる。

### マージ時のコンフリクト
同じファイルの同じ部分を二つのブランチで別々に変更し、それをマージしようとすると、Gitはそれをうまくマージできず、コンフリクトが発生する。コンフリクトを解決するまで、処理は中断される。

## ブランチの管理

`git branch`を何も引数を渡さずに実行すると、ブランチ一覧が表示される。*が現在チェックアウトされているブランチ (HEAD が指しているブランチ) を意味する。
また、`git branch -v`で各ブランチにおける直近のコミットを調べられ、`git branch --merged`や`git branch --no-merged`で現在作業中のブランチにマージ済みのもの (あるいはそうでないもの) だけを表示することができる。

### 長期稼働用ブランチ
完全に安定したコードのみをmasterブランチに置き、いつでもリリースできる状態にしておく。それ以外に並行してdevelopやnextといった名前のブランチを持ち、安定性をテストするためにそこを使用する。安定した状態になったら、それをmasterにマージすることになる。また、時にはトピックブランチ （短期間のブランチ) を作成し、すべてのテストに通ることやバグが発生していないことを確認することもある。大規模なプロジェクトでは、安定性のレベルに応じて何段階かのブランチを作成し、安定性が一段階上がった時点で上位レベルのブランチにマージしていくという方法がある。

### トピックブランチ
トピックブランチとは、短期間だけ使うブランチのことで、何か特定の機能やそれに関連する作業を行うために作成する。それぞれの作業が別のブランチに分離されており、そのブランチ内の変更は特定のトピックに関するものだけなので、コードレビューなどの作業が容易になる。そして一定の間ブランチで保持し続けた変更は、マージできるようになった時点で (ブランチを作成した順や作業した順に関係なく) すぐにマージする。

## リモートブランチ

リモート追跡ブランチとは、リモートブランチの状態を保持する参照である。ローカルに作成される参照だが、自分で移動することはできない。ネットワーク越しの操作をしたときに自動的に移動する。ブランチ名は (remote)/(branch) のようになる。たとえば、originサーバーに最後に接続したときのmasterブランチの状態を知りたければorigin/masterブランチをチェックする。
originサーバーとローカルでの作業を同期させるには、`git fetch origin`コマンドを実行する。このコマンドは、まずoriginサーバーを探し、まだ手元にないデータをすべて取得し、ローカルデータベースを更新し、origin/masterが指す先を最新の位置に変更する。ローカルのmasterブランチと同期するには`git merge origin/master`コマンドを実行して、ローカルのmasterブランチにorigin/masterをマージする。

### プッシュ
ブランチの内容を他者と共有するには、書き込み権限を持つどこかのリモートにそれをプッシュする。`git push <remote> <branch>`コマンドで実行できる。

### 追跡ブランチ
`git checkout -b [branch] [remotename]/[branch]`コマンドにより、[branch]という名の追跡ブランチをローカルに作成し、リモートブランチ[remotename]/[branch]を追跡できるようになる。`git checkout --track [remotename]/[branch]`コマンドがこれの短縮形である。
`git branch -vv`コマンドにより、ローカルブランチの一覧、各ブランチが追跡するリモートブランチ、リモートとの差異が表示される。

### プル
`git pull`コマンドは、`git fetch`の実行直後に`git merge`を実行するのと同じ動きになる。

### リモートブランチの削除
`git push origin --delete [branch]`コマンドによりoriginサーバーの[branch]ブランチを削除できる。

### リベースの基本
作業が二つに分岐した状況で、ブランチを統合するには、mergeとrebaseの二つの方法がある。rebaseでは、一方のブランチにコミットされたすべての変更をもう一方のブランチで再現する。これによりfast-forwardマージが可能となり、よりすっきりとした歴史になる。最後に行ったコミットが指すスナップショットは、リベースした結果の最後のコミットであっても、マージ後の最終のコミットであっても、同じものとなる。
次のように実行する。
```
$ git checkout experiment
$ git rebase master
```
これは、二つのブランチ (experimentとmaster）の共通の先祖に移動し、experimentブランチ上の各コミットのdiffを取得して一時ファイルに保存し、experimentブランチの指す先をリベース先のmasterブランチと同じコミットに移動させ、先ほどの変更を順に適用していくという過程になる。
また、`git rebase [basebranch] [topicbranch]`コマンドで、トピックブランチをチェックアウトして、その変更をベースブランチ上に再現できる。

### リベースの注意点
リベースを行う際の注意点は「公開リポジトリにプッシュしたコミットをリベースしてはいけない」ということである。
リベースをすると、既存のコミットを破棄して新たなコミットを作成することになる。プッシュしたコミットを誰かが取得して、その上で作業を始めているとする。`git rebase`でそのコミットを書き換えて再度プッシュすると、相手は再びマージすることになり、相手側の作業を自分の環境にプルしようとすると問題が発生する。
そのため、まだプッシュしていないローカルの変更だけをリベースするようにして、プッシュ済みの変更は決してリベースしないようにする。

### 参考
git --distributed-even-if-your-workflow-isnt
Gitのブランチ機能
https://git-scm.com/book/ja/v2/Git-%E3%81%AE%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E6%A9%9F%E8%83%BD-%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%81%A8%E3%81%AF

**Comment by GuiltyMorishita** [comment]
LGTM
